### ISSUE TITLE
Add possibility for custom title

### ISSUE THREAD

**Issue by lineke** [coreui/coreui-icons-vue#5]
I would love to see the possibility for a custom title for an icon instead of the iconName as currently is used. Is this planned for a future release?

**Comment by woothu** [comment]
Hi, thank you for your proposition!

We have added features regarding title generation in the [latest release](https://github.com/coreui/coreui-icons-vue/releases/tag/1.1.0)

Features: 
- add title prop that enables adding custom title text,
- changed text generated as title, when "title" prop is not defined:
   - If "name" prop is passed: title is generated based on "name" prop i.e. "cil-location-pin" will display title "Location Pin",  "custom-user-title" will display "Custom User Title",
   - If the "name" prop is not passed: title will be displayed as "icon"

---
This resolves also @rusicsemenov issue number #6

**Comment by rusicsemenov** [comment]
Yes i update icons-vue to 1.1 `"@coreui/icons-vue": "^1.1.0",`
But in coreui/vue steel show old title. I need rebuild vue core?

**Comment by woothu** [comment]
After npm update on template project, it would work only if you get CIcon component from 
```
@coreui/vue/src/CIconRaw.vue
```

@coreui/vue build files would be updated soon, with next beta release.

**Comment by rusicsemenov** [comment]
but @core/vue/src/components/index.js import CIcon from icon-vue
```
import CIcon from '@coreui/icons-vue/src/CIconRaw.vue'
export { CIcon }
```

**Comment by woothu** [comment]
You have right, I didn't looked up source ;)

**Comment by rusicsemenov** [comment]
Yes, but cicon dont updated.
Do you have discord chat or somthing also? ))
